version: '3'
services:
  service-name:
    # image: imageName
    container_name: my-container
    build:
      context: .
      dockerfile: Dockerfile.local
    # environment:
    #   - name=value
    env_file:
      - app/.env_file
    ports:
      - "8000:8000"
    volumes:
      - .:/app # Mount the current directory to the /app directory in the container
    command: "python app.py"