# Sample docker file for local development
FROM python:3.8-slim

WORKDIR /app

RUN apt-get update && apt-get install -y \
    build-essential \
    python=3.8 \
    pip

RUN rm -rf /var/lib/apt/lists/*

COPY requirements.txt .

RUN pip install -r requirements.txt

# No need to copy local directory for local development, will configure the volume mapping through docker-compose file
# COPY . .

# CMD ["python", "app.py"]